# DISCLAIMER: This is not an official SUSE product, and it is not supported by SUSE or the Harvester project.
# It is provided for exploration and evaluation only, as is and without warranty. Do not rely on it for production migrations.
# Addon manifest in the style of harvester/experimental-addons.
# Until the chart is published at charts.harvesterhci.io, point `repo` at the
# self-hosted chart repository (Phase 5a).
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: harvester-migration
  namespace: harvester-system
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://doccaz.github.io/harvester-migration-addon
  version: 0.5.1
  chart: harvester-migration
  valuesContent: |
    harvester-vm-import-controller:
      fullnameOverride: harvester-vm-import-controller
